# See http://www.appveyor.com/docs/appveyor-yml for many more options
version: 2.1.{build}


#Publish to PowerShell Gallery with the NuGetApiKey
#Communicate with StatusCake using the StatusCakeApiKey
environment:
  NuGetApiKey:
    secure: AIbS1wYpJuS5smWmeVDw5Bs9BmYV5q66BiJvg6hiJHHoELHnreIdclPuhBcaDdsS
  StatusCakeApiKey:
    secure: ZZmmlQfXYjLTWVrf1hChLh9Fefy6manSW8zj5bTRv30=

# Allow WMF5 (i.e. PowerShellGallery functionality)
os: WMF 5

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message 
skip_commits:
  message: /updated readme.*|update readme.*s/

build: false

#Build only on the master branch
branches:
  only:
    - master
    
#Kick off the CI/CD pipeline
test_script:
  - ps: . .\build.ps1